function mat = genArtheta(ID,btype,F,T,E,Sb,u0)

[g,b,~,tau,tshift,~,~] = branchparts_unpack(Sb,btype);
switch ID
    case 0
        mat = ...
        (-F'*diags(tau.^(-1))*diags(exp(T*u0).*( g.*sin(tshift) + b.*cos(tshift))) ...
         +T'*diags(tau.^(-1))*diags(exp(F*u0).*(-g.*sin(tshift) + b.*cos(tshift))))*E;
    case 1
        mat = ...
        (-F'*diags(exp(T*u0).*( g.*sin(tshift) + b.*cos(tshift))) ...
         +T'*diags(exp(F*u0).*(-g.*sin(tshift) + b.*cos(tshift))))*E;
    case 2
        mat = ...
        (-F'*diags( g.*sin(tshift) + b.*cos(tshift)) ...
         +T'*diags(-g.*sin(tshift) + b.*cos(tshift)))*E;
    case 3
        mat = ...
        (-F'*diags(exp(T*u0).* b.* cos(tshift)) ...
         +T'*diags(exp(F*u0).* b.* cos(tshift)))*E;
    case 4
        mat = ...
        (-F'*diags( b.* cos(tshift)) ...
         +T'*diags( b.* cos(tshift)))*E;
    otherwise
        error('Incorrect ID')
end