function s = ids2str(ids)

if length(fieldnames(ids)) == 13
	s = sprintf('%d%d%d%d%d%d%d%d%d%d%d%d%d',ids.iter,...
	    ids.Art,ids.Artb,ids.Aru,ids.Arub,...
	    ids.Amt,ids.Amtb,ids.Amu,ids.Amub,...
	    ids.br, ids.brb, ids.bm, ids.bmb);
elseif length(fieldnames(ids)) == 12
	s = sprintf('%d%d%d%d%d%d%d%d%d%d%d%d', ids.iter,...
			ids.Q, ids.AB, ids.c, ids.gr, ids.gi,...
			ids.Omr, ids.Gami, ids.Kr, ids.Omi, ids.Gamr, ids.Ki);
else
	error('unknow number of fields in id: %d', length(fieldnames(ids)))
end
